# Generated by Django 4.2.7 on 2023-11-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foydalanuvchi',
            new_name='Izoh',
        ),
    ]
